baseURL = 'https://docs.cosmosgame.space/'
languageCode = 'en-us'
title = 'Cosmos API Docs'

# Code higlighting settings
pygmentsCodefences            = true
pygmentsCodeFencesGuesSyntax  = false
pygmentsOptions               = ""
pygmentsStyle                 = "monokai"
pygmentsUseClasses            = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
      unsafe = true

[[module.imports]]
path = "github.com/bep/docuapi/v2"

[params]
  search       = true
  maxMenuDepth = 3    # (optional) available options are: 1, 2, or 3 (default: 2)

  # Configure the language example tabs.
  [[params.language_tabs]]
    key  = "go"
    name = "Go"
  [[params.language_tabs]]
    key  = "shell"
    name = "Shell"
  [[params.language_tabs]]
    key  = "python"
    name = "Python"